// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: telemetry.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ThreatIntelligence_StreamEvents_FullMethodName = "/entce.ThreatIntelligence/StreamEvents"
)

// ThreatIntelligenceClient is the client API for ThreatIntelligence service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Enterprise Threat Telemetry service
type ThreatIntelligenceClient interface {
	// Stream telemetry from the probe to the control plane
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SecurityEvent, MitigationAction], error)
}

type threatIntelligenceClient struct {
	cc grpc.ClientConnInterface
}

func NewThreatIntelligenceClient(cc grpc.ClientConnInterface) ThreatIntelligenceClient {
	return &threatIntelligenceClient{cc}
}

func (c *threatIntelligenceClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SecurityEvent, MitigationAction], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ThreatIntelligence_ServiceDesc.Streams[0], ThreatIntelligence_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SecurityEvent, MitigationAction]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ThreatIntelligence_StreamEventsClient = grpc.BidiStreamingClient[SecurityEvent, MitigationAction]

// ThreatIntelligenceServer is the server API for ThreatIntelligence service.
// All implementations must embed UnimplementedThreatIntelligenceServer
// for forward compatibility.
//
// The Enterprise Threat Telemetry service
type ThreatIntelligenceServer interface {
	// Stream telemetry from the probe to the control plane
	StreamEvents(grpc.BidiStreamingServer[SecurityEvent, MitigationAction]) error
	mustEmbedUnimplementedThreatIntelligenceServer()
}

// UnimplementedThreatIntelligenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedThreatIntelligenceServer struct{}

func (UnimplementedThreatIntelligenceServer) StreamEvents(grpc.BidiStreamingServer[SecurityEvent, MitigationAction]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedThreatIntelligenceServer) mustEmbedUnimplementedThreatIntelligenceServer() {}
func (UnimplementedThreatIntelligenceServer) testEmbeddedByValue()                            {}

// UnsafeThreatIntelligenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThreatIntelligenceServer will
// result in compilation errors.
type UnsafeThreatIntelligenceServer interface {
	mustEmbedUnimplementedThreatIntelligenceServer()
}

func RegisterThreatIntelligenceServer(s grpc.ServiceRegistrar, srv ThreatIntelligenceServer) {
	// If the following call panics, it indicates UnimplementedThreatIntelligenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ThreatIntelligence_ServiceDesc, srv)
}

func _ThreatIntelligence_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ThreatIntelligenceServer).StreamEvents(&grpc.GenericServerStream[SecurityEvent, MitigationAction]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ThreatIntelligence_StreamEventsServer = grpc.BidiStreamingServer[SecurityEvent, MitigationAction]

// ThreatIntelligence_ServiceDesc is the grpc.ServiceDesc for ThreatIntelligence service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThreatIntelligence_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "entce.ThreatIntelligence",
	HandlerType: (*ThreatIntelligenceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _ThreatIntelligence_StreamEvents_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "telemetry.proto",
}
