// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: telemetry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MitigationAction_ActionType int32

const (
	MitigationAction_OBSERVE      MitigationAction_ActionType = 0
	MitigationAction_RATE_LIMIT   MitigationAction_ActionType = 1
	MitigationAction_KILL_PROCESS MitigationAction_ActionType = 2
	MitigationAction_SHUN_IP      MitigationAction_ActionType = 3
)

// Enum value maps for MitigationAction_ActionType.
var (
	MitigationAction_ActionType_name = map[int32]string{
		0: "OBSERVE",
		1: "RATE_LIMIT",
		2: "KILL_PROCESS",
		3: "SHUN_IP",
	}
	MitigationAction_ActionType_value = map[string]int32{
		"OBSERVE":      0,
		"RATE_LIMIT":   1,
		"KILL_PROCESS": 2,
		"SHUN_IP":      3,
	}
)

func (x MitigationAction_ActionType) Enum() *MitigationAction_ActionType {
	p := new(MitigationAction_ActionType)
	*p = x
	return p
}

func (x MitigationAction_ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MitigationAction_ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_telemetry_proto_enumTypes[0].Descriptor()
}

func (MitigationAction_ActionType) Type() protoreflect.EnumType {
	return &file_telemetry_proto_enumTypes[0]
}

func (x MitigationAction_ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MitigationAction_ActionType.Descriptor instead.
func (MitigationAction_ActionType) EnumDescriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1, 0}
}

// Data captured at the kernel level by eBPF
type SecurityEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // e.g., "PROCESS_EXEC", "SOCKET_CONNECT"
	SourceIp      string                 `protobuf:"bytes,4,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	CommandLine   string                 `protobuf:"bytes,5,opt,name=command_line,json=commandLine,proto3" json:"command_line,omitempty"` // The full command executed
	ProcessId     int32                  `protobuf:"varint,6,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	Metadata      string                 `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"` // JSON string for additional context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityEvent) Reset() {
	*x = SecurityEvent{}
	mi := &file_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityEvent) ProtoMessage() {}

func (x *SecurityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityEvent.ProtoReflect.Descriptor instead.
func (*SecurityEvent) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *SecurityEvent) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SecurityEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *SecurityEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SecurityEvent) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *SecurityEvent) GetCommandLine() string {
	if x != nil {
		return x.CommandLine
	}
	return ""
}

func (x *SecurityEvent) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *SecurityEvent) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

// Actions returned by the AI agents
type MitigationAction struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Type          MitigationAction_ActionType `protobuf:"varint,1,opt,name=type,proto3,enum=entce.MitigationAction_ActionType" json:"type,omitempty"`
	Target        string                      `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`                               // The IP or PID to act upon
	Reasoning     string                      `protobuf:"bytes,3,opt,name=reasoning,proto3" json:"reasoning,omitempty"`                         // The AI's explanation
	DurationSec   int32                       `protobuf:"varint,4,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"` // Reversible action timeout
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MitigationAction) Reset() {
	*x = MitigationAction{}
	mi := &file_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MitigationAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MitigationAction) ProtoMessage() {}

func (x *MitigationAction) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MitigationAction.ProtoReflect.Descriptor instead.
func (*MitigationAction) Descriptor() ([]byte, []int) {
	return file_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *MitigationAction) GetType() MitigationAction_ActionType {
	if x != nil {
		return x.Type
	}
	return MitigationAction_OBSERVE
}

func (x *MitigationAction) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MitigationAction) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *MitigationAction) GetDurationSec() int32 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

var File_telemetry_proto protoreflect.FileDescriptor

const file_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x0ftelemetry.proto\x12\x05entce\"\xe4\x01\n" +
	"\rSecurityEvent\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12\x1b\n" +
	"\tsource_ip\x18\x04 \x01(\tR\bsourceIp\x12!\n" +
	"\fcommand_line\x18\x05 \x01(\tR\vcommandLine\x12\x1d\n" +
	"\n" +
	"process_id\x18\x06 \x01(\x05R\tprocessId\x12\x1a\n" +
	"\bmetadata\x18\a \x01(\tR\bmetadata\"\xed\x01\n" +
	"\x10MitigationAction\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".entce.MitigationAction.ActionTypeR\x04type\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x1c\n" +
	"\treasoning\x18\x03 \x01(\tR\treasoning\x12!\n" +
	"\fduration_sec\x18\x04 \x01(\x05R\vdurationSec\"H\n" +
	"\n" +
	"ActionType\x12\v\n" +
	"\aOBSERVE\x10\x00\x12\x0e\n" +
	"\n" +
	"RATE_LIMIT\x10\x01\x12\x10\n" +
	"\fKILL_PROCESS\x10\x02\x12\v\n" +
	"\aSHUN_IP\x10\x032W\n" +
	"\x12ThreatIntelligence\x12A\n" +
	"\fStreamEvents\x12\x14.entce.SecurityEvent\x1a\x17.entce.MitigationAction(\x010\x01B Z\x1egithub.com/entce-x/probe/protob\x06proto3"

var (
	file_telemetry_proto_rawDescOnce sync.Once
	file_telemetry_proto_rawDescData []byte
)

func file_telemetry_proto_rawDescGZIP() []byte {
	file_telemetry_proto_rawDescOnce.Do(func() {
		file_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)))
	})
	return file_telemetry_proto_rawDescData
}

var file_telemetry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_telemetry_proto_goTypes = []any{
	(MitigationAction_ActionType)(0), // 0: entce.MitigationAction.ActionType
	(*SecurityEvent)(nil),            // 1: entce.SecurityEvent
	(*MitigationAction)(nil),         // 2: entce.MitigationAction
}
var file_telemetry_proto_depIdxs = []int32{
	0, // 0: entce.MitigationAction.type:type_name -> entce.MitigationAction.ActionType
	1, // 1: entce.ThreatIntelligence.StreamEvents:input_type -> entce.SecurityEvent
	2, // 2: entce.ThreatIntelligence.StreamEvents:output_type -> entce.MitigationAction
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_telemetry_proto_init() }
func file_telemetry_proto_init() {
	if File_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_proto_rawDesc), len(file_telemetry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_telemetry_proto_goTypes,
		DependencyIndexes: file_telemetry_proto_depIdxs,
		EnumInfos:         file_telemetry_proto_enumTypes,
		MessageInfos:      file_telemetry_proto_msgTypes,
	}.Build()
	File_telemetry_proto = out.File
	file_telemetry_proto_goTypes = nil
	file_telemetry_proto_depIdxs = nil
}
