# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: telemetry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'telemetry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftelemetry.proto\x12\x05\x65ntce\"\x98\x01\n\rSecurityEvent\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x12\n\nevent_type\x18\x03 \x01(\t\x12\x11\n\tsource_ip\x18\x04 \x01(\t\x12\x14\n\x0c\x63ommand_line\x18\x05 \x01(\t\x12\x12\n\nprocess_id\x18\x06 \x01(\x05\x12\x10\n\x08metadata\x18\x07 \x01(\t\"\xc7\x01\n\x10MitigationAction\x12\x30\n\x04type\x18\x01 \x01(\x0e\x32\".entce.MitigationAction.ActionType\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\x11\n\treasoning\x18\x03 \x01(\t\x12\x14\n\x0c\x64uration_sec\x18\x04 \x01(\x05\"H\n\nActionType\x12\x0b\n\x07OBSERVE\x10\x00\x12\x0e\n\nRATE_LIMIT\x10\x01\x12\x10\n\x0cKILL_PROCESS\x10\x02\x12\x0b\n\x07SHUN_IP\x10\x03\x32W\n\x12ThreatIntelligence\x12\x41\n\x0cStreamEvents\x12\x14.entce.SecurityEvent\x1a\x17.entce.MitigationAction(\x01\x30\x01\x42 Z\x1egithub.com/entce-x/probe/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'telemetry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036github.com/entce-x/probe/proto'
  _globals['_SECURITYEVENT']._serialized_start=27
  _globals['_SECURITYEVENT']._serialized_end=179
  _globals['_MITIGATIONACTION']._serialized_start=182
  _globals['_MITIGATIONACTION']._serialized_end=381
  _globals['_MITIGATIONACTION_ACTIONTYPE']._serialized_start=309
  _globals['_MITIGATIONACTION_ACTIONTYPE']._serialized_end=381
  _globals['_THREATINTELLIGENCE']._serialized_start=383
  _globals['_THREATINTELLIGENCE']._serialized_end=470
# @@protoc_insertion_point(module_scope)
