# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import telemetry_pb2 as telemetry__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ThreatIntelligenceStub(object):
    """The Enterprise Threat Telemetry service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamEvents = channel.stream_stream(
                '/entce.ThreatIntelligence/StreamEvents',
                request_serializer=telemetry__pb2.SecurityEvent.SerializeToString,
                response_deserializer=telemetry__pb2.MitigationAction.FromString,
                _registered_method=True)


class ThreatIntelligenceServicer(object):
    """The Enterprise Threat Telemetry service
    """

    def StreamEvents(self, request_iterator, context):
        """Stream telemetry from the probe to the control plane
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ThreatIntelligenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamEvents': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=telemetry__pb2.SecurityEvent.FromString,
                    response_serializer=telemetry__pb2.MitigationAction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'entce.ThreatIntelligence', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('entce.ThreatIntelligence', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ThreatIntelligence(object):
    """The Enterprise Threat Telemetry service
    """

    @staticmethod
    def StreamEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/entce.ThreatIntelligence/StreamEvents',
            telemetry__pb2.SecurityEvent.SerializeToString,
            telemetry__pb2.MitigationAction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
